version: '3.0'

expectations:
  population_size: 2000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_part1
    outputs:
      highly_sensitive:
        cohort: output/input_part1.csv
