version: '3.0'

expectations:
  population_size: 5000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_part1
    outputs:
      highly_sensitive:
        cohort: output/input_part1.csv

  data_cleaning:
    run: stata-mp:latest analysis/010_cleaning.do
    needs: [generate_cohort]
    outputs:
      highly_sensitive:
        analysis_dataset: output/input_part1_clean.dta

  matching_groups_1_and_2:
    run: stata-mp:latest analysis/021_matching_groups_1_and_2.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_2.dta

  matching_groups_1_and_3:
    run: stata-mp:latest analysis/022_matching_groups_1_and_3.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_3.dta

  matching_groups_3_and_4:
    run: stata-mp:latest analysis/022_matching_groups_3_and_4.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_3_and_4.dta

  analyses_table1:
    run: stata-mp:latest analysis/031_analyses_table1.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/table1_demographics.dta