version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_part1
    outputs:
      highly_sensitive:
        cohort: output/input_part1.csv

  data_cleaning:
    run: stata-mp:latest analysis/010_cleaning.do
    needs: [generate_cohort]
    outputs:
      highly_sensitive:
        analysis_dataset: output/input_part1_clean.dta

  matching_groups_1_and_2:
    run: stata-mp:latest analysis/021_matching_groups_1_and_2.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_2.dta

  matching_groups_1_and_3:
    run: stata-mp:latest analysis/022_matching_groups_1_and_3.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_3.dta

  matching_groups_1_2_and_3:
    run: stata-mp:latest analysis/023_matching_groups_1_2_and_3.do
    needs: [matching_groups_1_and_2, matching_groups_1_and_3]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_2_and_3.dta

  analyses_option1_table1:
    run: stata-mp:latest analysis/110_analyses_option1_table1_demographics.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table1_demographics.dta

  analyses_option1_table2:
    run: stata-mp:latest analysis/120_analyses_option1_table2_rates.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table2_rates.dta

  analyses_option1_table3:
    run: stata-mp:latest analysis/130_analyses_option1_table3_hazardratios.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table3_hazardratios.dta

  analyses_option1_table4:
    run: stata-mp:latest analysis/140_analyses_option1_table4_stratified_rates.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table4_stratified_rates.dta

  analyses_option1_table5:
    run: stata-mp:latest analysis/150_analyses_option1_table5_stratified_hazardratios.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table5_stratified_hazardratios.dta    

  analyses_option2_table1a:
    run: stata-mp:latest analysis/210_analyses_option2_table1a_demographics_groups_1_and_2.do
    needs: [matching_groups_1_and_2]
    outputs:
      moderately_sensitive:
        table1: output/results/option2_table1a_demographics_groups_1_and_2.dta

  analyses_option2_table1b:
    run: stata-mp:latest analysis/211_analyses_option2_table1b_demographics_groups_1_and_3.do
    needs: [matching_groups_1_and_3]
    outputs:
      moderately_sensitive:
        table1: output/results/option2_table1b_demographics_groups_1_and_3.dta

  analyses_option3_table1:
    run: stata-mp:latest analysis/310_analyses_option3_table1_demographics.do
    needs: [matching_groups_1_2_and_3]
    outputs:
      moderately_sensitive:
        table1: output/results/option3_table1_demographics.dta

  redaction:
    run: stata-mp:latest analysis/999_redaction.do
    needs: [analyses_option1_table1, analyses_option1_table2, analyses_option1_table3, analyses_option1_table4, analyses_option1_table5, analyses_option2_table1a, analyses_option2_table1b, analyses_option3_table1]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table1_demographics_redacted.dta
        table2: output/results/option1_table1_demographics_redacted.csv
        table3: output/results/option1_table2_rates_redacted.dta
        table4: output/results/option1_table2_rates_redacted.csv
        #table5: output/results/option1_table3_hazardratios_redacted.dta
        #table6: output/results/option1_table3_hazardratios_redacted.csv
        #table7: output/results/option1_table4_stratified_rates_redacted.dta
        #table8: output/results/option1_table4_stratified_rates_redacted.csv
        #table9: output/results/option1_table5_stratified_hazardratios_redacted.dta
        #table10: output/results/option1_table5_stratified_hazardratios_redacted.csv
        #table11: output/results/option2_table1a_demographics_groups_1_and_2_redacted.dta
        #table12: output/results/option2_table1a_demographics_groups_1_and_2_redacted.csv
        #table13: output/results/option2_table1b_demographics_groups_1_and_3_redacted.dta
        #table14: output/results/option2_table1b_demographics_groups_1_and_3_redacted.csv
        #table15: output/results/option3_table1_demographics_redacted.dta
        #table16: output/results/option3_table1_demographics_redacted.csv       
