version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_part1
    outputs:
      highly_sensitive:
        cohort: output/input_part1.csv

  data_cleaning:
    run: stata-mp:latest analysis/010_cleaning.do
    needs: [generate_cohort]
    outputs:
      highly_sensitive:
        analysis_dataset: output/input_part1_clean.dta

  matching_groups_1_and_2:
    run: stata-mp:latest analysis/021_matching_groups_1_and_2.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_2.dta

  matching_groups_1_and_3:
    run: stata-mp:latest analysis/022_matching_groups_1_and_3.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_3.dta

  matching_groups_1_2_and_3:
    run: stata-mp:latest analysis/023_matching_groups_1_2_and_3.do
    needs: [matching_groups_1_and_2, matching_groups_1_and_3]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_2_and_3.dta

  analyses_option1_table1:
    run: stata-mp:latest analysis/110_analyses_option1_table1_demographics.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table1_demographics.dta

  analyses_option1_table2b:
    run: stata-mp:latest analysis/121_analyses_option1_table2b_rateratios.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table2b_rateratios.dta

  analyses_option1_table4b:
    run: stata-mp:latest analysis/141_analyses_option1_table4b_stratified_rateratios.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table4b_stratified_rateratios.dta

  analyses_option1_table6:
    run: stata-mp:latest analysis/160_analyses_option1_table6_periodspecific_rates.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table6_periodspecific_rates.dta

  analyses_option1_table8:
    run: stata-mp:latest analysis/180_analyses_option1_table8_splitfollowup_rates.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table1: output/results/option1_table8_splitfollowup_rates.dta

  generate_cohort_2:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_part2
    outputs:
      highly_sensitive:
        cohort: output/input_part2.csv
