version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_part1
    outputs:
      highly_sensitive:
        cohort: output/input_part1.csv

  data_cleaning:
    run: stata-mp:latest analysis/001_cleaning.do
    needs: [generate_cohort]
    outputs:
      highly_sensitive:
        analysis_dataset: output/input_part1_clean.dta

  matching_groups_1_and_2:
    run: stata-mp:latest analysis/002_matching_groups_1_and_2.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_2.dta