version: '3.0'

expectations:
  population_size: 100000

actions:

  generate_cohort:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_part1
    outputs:
      highly_sensitive:
        cohort: output/input_part1.csv

  data_cleaning:
    run: stata-mp:latest analysis/010_cleaning.do
    needs: [generate_cohort]
    outputs:
      highly_sensitive:
        analysis_dataset: output/input_part1_clean.dta

  matching_groups_1_and_2:
    run: stata-mp:latest analysis/021_matching_groups_1_and_2.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_2.dta

  matching_groups_1_and_3:
    run: stata-mp:latest analysis/022_matching_groups_1_and_3.do
    needs: [data_cleaning]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_and_3.dta

  matching_groups_1_2_and_3:
    run: stata-mp:latest analysis/023_matching_groups_1_2_and_3.do
    needs: [matching_groups_1_and_3]
    outputs:
      highly_sensitive:
        analysis_dataset: output/matched_groups_1_2_and_3.dta

  analyses_option1_table1:
    run: stata-mp:latest analysis/110_analyses_option1_table1_demog.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        analysis_dataset: output/part1/option1_table1_demographics.dta

  analyses_option1_table2:
    run: stata-mp:latest analysis/120_analyses_option1_table2_rates.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table: output/part1/option1_table2_rates.dta

  analyses_option1_table3:
    run: stata-mp:latest analysis/130_analyses_option1_table3_hazardratios.do
    needs: [data_cleaning]
    outputs:
      moderately_sensitive:
        table: output/part1/option1_table3_hazardratios.dta