replace demographic="Sex" if demographic=="sex"
replace demographic="Age" if demographic=="age"
replace demographic="Ethnicity" if demographic=="ethnic"
replace demographic="IMD" if demographic=="imd"
replace demographic="Type of Diabetes" if demographic=="diabetes"
replace demographic="History of CVD" if demographic=="hist_cvd"
replace demographic="History of renal disease" if demographic=="hist_renal"
replace demographic="Required critical care" if demographic=="critical"
replace demographic="Smoking status" if demographic=="smoking"
replace demographic="Hazardous alcohol consumption" if demographic=="alcohol"
replace demographic="BMI" if demographic=="bmi"
replace demographic="HbA1c" if demographic=="hba1c"
replace demographic="COVID-19 vaccination status" if demographic=="vaccin"
