replace outcome="Stroke: Thrombotic/ischaemic" 					if outcome=="stroke_thrombotic"
replace outcome="Stroke: Haemorrhagic"							if outcome=="stroke_haemorrhagic"
replace outcome="Stroke: TIA"									if outcome=="stroke_tia"
replace outcome="Stroke: In pregnancy or puerperium"			if outcome=="stroke_pregnancy"
replace outcome="Stroke: Any"									if outcome=="stroke_any"
replace outcome="MI" 											if outcome=="mi"
replace outcome="DVT: Not pregnancy-related" 					if outcome=="dvt_nopregnancy"
replace outcome="DVT: In pregnancy or puerperium"				if outcome=="dvt_pregnancy"
replace outcome="DVT: Cerebral venous thrombosis in pregnancy"	if outcome=="dvt_pregnancy_cvt"
replace outcome="DVT: Any"										if outcome=="dvt_any"
replace outcome="PE: Not pregnancy-related" 					if outcome=="pe_nopregnancy"
replace outcome="PE: In pregnancy or puerperium"				if outcome=="pe_pregnancy"
replace outcome="PE: Any"										if outcome=="pe_any"
replace outcome="Heart Failure" 								if outcome=="heart_failure"		| outcome=="hf"
replace outcome="Any"											if outcome=="any_cvd"
replace outcome="AKI: Not pregnancy-related" 					if outcome=="aki_nopregnancy"
replace outcome="AKI: In pregnancy or puerperium"				if outcome=="aki_pregnancy"
replace outcome="AKI: Any"										if outcome=="aki_any"
replace outcome="Liver disease/failure" 						if outcome=="liver"
replace outcome="Anxiety" 										if outcome=="anxiety"
replace outcome="Depression" 									if outcome=="depression"
replace outcome="Affective/non-affective psychosis" 			if outcome=="psychosis"
replace outcome="Psychotropic medication: Antidepressant" 		if outcome=="antidepressant"
replace outcome="Psychotropic medication: Anxiolytic" 			if outcome=="anxiolytic"
replace outcome="Psychotropic medication: Antipsychotic" 		if outcome=="antipsychotic"
replace outcome="Psychotropic medication: Mood stabiliser" 		if outcome=="mood_stabiliser"
replace outcome="Sleep disorder: Insomnia"						if outcome=="sleep_insomnia"
replace outcome="Sleep disorder: Hypersomnia"					if outcome=="sleep_hypersomnia"
replace outcome="Sleep disorder: Apnoea"						if outcome=="sleep_apnoea"
replace outcome="Fatigue" 										if outcome=="fatigue"
