replace outcome="Stroke" 					if outcome=="stroke"
replace outcome="MI" 						if outcome=="mi"
replace outcome="DVT" 						if outcome=="dvt"
replace outcome="PE" 						if outcome=="pe"
replace outcome="Heart Failure" 			if outcome=="heart_failure"		| outcome=="hf"
replace outcome="Any"						if outcome=="any_cvd"
replace outcome="AKI" 						if outcome=="aki"
replace outcome="Liver Failure" 			if outcome=="liver_failure"
replace outcome="Chronic Liver Disease" 	if outcome=="chronic_liver"
replace outcome="Anxiety" 					if outcome=="anxiety"
replace outcome="Depression" 				if outcome=="depression"
replace outcome="Psychosis" 				if outcome=="psychosis"
replace outcome="Psychotropic Medication" 	if outcome=="psych_meds"
replace outcome="Insomnia" 					if outcome=="insomnia"
replace outcome="Hypersomnia" 				if outcome=="hypersomnia"
replace outcome="Sleep Apnoea" 				if outcome=="sleep_apnoea"
replace outcome="Sleep Medication" 			if outcome=="sleep_meds"
replace outcome="Fatigue-like Syndrome" 	if outcome=="fatigue_syndr"