replace type="Cardiovascular" 					if outcome=="Stroke" 					| outcome=="stroke"
replace type="Cardiovascular" 					if outcome=="MI" 						| outcome=="mi"
replace type="Cardiovascular" 					if outcome=="DVT" 						| outcome=="dvt"
replace type="Cardiovascular" 					if outcome=="PE" 						| outcome=="pe"
replace type="Cardiovascular" 					if outcome=="Heart Failure" 			| outcome=="heart_failure"
replace type="Renal" 							if outcome=="AKI" 						| outcome=="aki"
replace type="Hepatic" 							if outcome=="Liver Failure" 			| outcome=="liver_failure"
replace type="Hepatic" 							if outcome=="Chronic Liver Disease" 	| outcome=="chronic_liver"
replace type="Mental illness" 					if outcome=="Anxiety" 					| outcome=="anxiety"
replace type="Mental illness" 					if outcome=="Depression" 				| outcome=="depression"
replace type="Mental illness" 					if outcome=="Psychosis" 				| outcome=="psychosis"
replace type="Mental illness" 					if outcome=="Psychotropic Medication" 	| outcome=="psych_meds"
replace type="Symptoms of post-COVID syndrome" 	if outcome=="Insomnia" 					| outcome=="insomnia"
replace type="Symptoms of post-COVID syndrome" 	if outcome=="Hypersomnia" 				| outcome=="hypersomnia"
replace type="Symptoms of post-COVID syndrome" 	if outcome=="Sleep Apnoea" 				| outcome=="sleep_apnoea"
replace type="Symptoms of post-COVID syndrome" 	if outcome=="Sleep Medication" 			| outcome=="sleep_meds"
replace type="Symptoms of post-COVID syndrome" 	if outcome=="Fatigue-like Syndrome" 	| outcome=="fatigue_syndr"
replace type="Death from any cause" 			if outcome=="Death" 					| outcome=="death"