replace type="Cardiovascular" if outcome=="Stroke: Thrombotic/ischaemic"
replace type="Cardiovascular" if outcome=="Stroke: Haemorrhagic"
replace type="Cardiovascular" if outcome=="Stroke: TIA"
replace type="Cardiovascular" if outcome=="Stroke: In pregnancy or puerperium"
replace type="Cardiovascular" if outcome=="Stroke: Any"
replace type="Cardiovascular" if outcome=="MI"
replace type="Cardiovascular" if outcome=="DVT: Not pregnancy-related"
replace type="Cardiovascular" if outcome=="DVT: In pregnancy or puerperium"
replace type="Cardiovascular" if outcome=="DVT: Cerebral venous thrombosis in pregnancy"
replace type="Cardiovascular" if outcome=="DVT: Any"
replace type="Cardiovascular" if outcome=="PE: Not pregnancy-related"
replace type="Cardiovascular" if outcome=="PE: In pregnancy or puerperium"
replace type="Cardiovascular" if outcome=="PE: Any"
replace type="Cardiovascular" if outcome=="Heart Failure"
replace type="Cardiovascular" if outcome=="Any"
replace type="Renal" if outcome=="AKI: Not pregnancy-related"
replace type="Renal" if outcome=="AKI: In pregnancy or puerperium"
replace type="Renal" if outcome=="AKI: Any"
replace type="Hepatic" if outcome=="Liver disease/failure"
replace type="Mental illness" if outcome=="Anxiety"
replace type="Mental illness" if outcome=="Depression"
replace type="Mental illness" if outcome=="Affective/non-affective psychosis"
replace type="Mental illness" if outcome=="Psychotropic medication: Antidepressant"
replace type="Mental illness" if outcome=="Psychotropic medication: Anxiolytic"
replace type="Mental illness" if outcome=="Psychotropic medication: Antipsychotic"
replace type="Mental illness" if outcome=="Psychotropic medication: Mood stabiliser"
replace type="Symptoms of post-COVID syndrome" if outcome=="Sleep disorder: Insomnia"
replace type="Symptoms of post-COVID syndrome" if outcome=="Sleep disorder: Hypersomnia"
replace type="Symptoms of post-COVID syndrome" if outcome=="Sleep disorder: Apnoea"
replace type="Symptoms of post-COVID syndrome" if outcome=="Fatigue"
replace type="Death from any cause" if outcome=="Death" | outcome=="death"
